import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavbarProvider } from "@/components/NavbarProvider/NavbarProvider";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://telegram.org/js/telegram-web-app.js" async></script>
      </head>
      <body className={inter.className}>
        <Suspense>
          <NavbarProvider>{children}</NavbarProvider>
        </Suspense>
      </body>
    </html>
  );
}
