name: zayna

services:
  client:
    build:
      context: .
      dockerfile: services/client/Dockerfile
      target: production
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    networks:
      - my-network

  node_backend:
    build:
      context: .
      dockerfile: services/node_backend/Dockerfile
      target: development
    env_file:
      - .env.local

  web:
    build:
      context: backend
      target: builder
    ports:
      - '8000:8000'
    networks:
      - my-network

  celery:
    build: .
    container_name: celery
    command: celery -A zayna worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=backend.settings

  celery-beat:
    build: .
    container_name: celery-beat
    command: celery -A zayna beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=backend.settings

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"

networks:
  my-network:
    driver: bridge