name: zayna

services:
  client:
    build:
      context: .
      dockerfile: services/client/Dockerfile
      target: development
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    volumes:
      - ./services/client:/app/client
      - /app/client/node_modules
    networks:
      - my-network

  node_backend:
    build:
      context: .
      dockerfile: services/node_backend/Dockerfile
      target: development
    env_file:
      - .env.local
    volumes:
      - ./services/node_backend:/app/node_backend
      - /app/node_backend/node_modules

  web:
    build:
      context: backend
      target: builder
    ports:
      - '8000:8000'
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
