name: zayna

services:
  client:
    build:
      context: .
      dockerfile: services/client/Dockerfile
      target: production
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    networks:
      - my-network

  node_backend:
    build:
      context: .
      dockerfile: services/node_backend/Dockerfile
      target: development
    env_file:
      - .env.local

  web:
    build:
      context: backend
      target: builder
    ports:
      - '8000:8000'
    networks:
      - my-network

networks:
  my-network:
    driver: bridge