# Generated by Django 4.2.13 on 2024-08-20 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0002_refferer"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tokens",
            field=models.TextField(default="0"),
        ),
        migrations.CreateModel(
            name="TokensBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tokens_count", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zayna.user"
                    ),
                ),
            ],
        ),
    ]
