# Generated by Django 4.2.13 on 2024-08-20 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0003_tokens_batch"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="tokens",
            new_name="tokens_count",
        ),
        migrations.AlterField(
            model_name="tokensbatch",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batches",
                to="zayna.user",
            ),
        ),
    ]
