# Generated by Django 4.2.13 on 2024-08-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0004_bathes_related_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokensbatch",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
