# Generated by Django 4.2.13 on 2024-09-04 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0005_tokens_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Present",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tokens_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presents",
                        to="zayna.user",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zayna.user"
                    ),
                ),
            ],
        ),
    ]
