# Generated by Django 4.2.13 on 2024-09-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0006_present"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("tokens_count", models.IntegerField(default=0)),
            ],
        ),
    ]
