# Generated by Django 4.2.13 on 2024-09-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0009_income"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="users",
            field=models.ManyToManyField(
                default=None, related_name="projects", to="zayna.user"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="income",
            field=models.IntegerField(default=0),
        ),
    ]
