# Generated by Django 4.2.13 on 2024-09-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0010_projects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="users",
            field=models.ManyToManyField(
                blank=True, default=None, related_name="projects", to="zayna.user"
            ),
        ),
    ]
