# Generated by Django 4.2.13 on 2024-09-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0011_null_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="friends",
            field=models.ManyToManyField(blank=True, to="zayna.user"),
        ),
    ]
