# Generated by Django 4.2.13 on 2024-09-07 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0013_normal_present"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="present",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="present",
            name="receiver",
        ),
    ]
