# Generated by Django 4.2.13 on 2024-09-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0014_del_fields_from_present"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="level",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos"),
        ),
        migrations.AddField(
            model_name="project",
            name="mode",
            field=models.CharField(
                choices=[
                    ("Forests", "Forests"),
                    ("Transport", "Transport"),
                    ("Energy", "Energy"),
                    ("Wastes", "Wastes"),
                ],
                default="Forests",
                max_length=10,
            ),
        ),
    ]
