# Generated by Django 4.2.13 on 2024-09-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0015_project_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
