# Generated by Django 4.2.13 on 2024-09-07 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0016_user_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="user",
            name="daily_combo",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="daily_reward_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 7, 16, 8, 46, 288709, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="income_updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 7, 16, 8, 46, 288684, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
