# Generated by Django 4.2.13 on 2024-09-07 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0017_user_daily"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="daily_reward_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 7, 16, 9, 34, 172985, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="income_updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 7, 16, 9, 34, 172972, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
