# Generated by Django 4.2.13 on 2024-09-07 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0018_user_daily"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="daily_reward_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="user",
            name="income_updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
