# Generated by Django 4.2.13 on 2024-09-07 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0019_user_default_now"),
    ]

    operations = [
        migrations.AddField(
            model_name="present",
            name="receiver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="presents",
                to="zayna.user",
            ),
        ),
        migrations.AddField(
            model_name="present",
            name="shown",
            field=models.BooleanField(default=False),
        ),
    ]
