# Generated by Django 4.2.13 on 2024-09-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0020_shown_present"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_game_at",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
