# Generated by Django 4.2.13 on 2024-09-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0021_last_game_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_game_won",
            field=models.BooleanField(default=False),
        ),
    ]
