# Generated by Django 4.2.13 on 2024-09-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0022_last_game_won"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.TextField(blank=True, default=""),
        ),
    ]
