# Generated by Django 4.2.13 on 2024-09-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0023_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.TextField(default=None, null=True),
        ),
    ]
