# Generated by Django 4.2.13 on 2024-09-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0024_null_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="mode",
            field=models.CharField(
                choices=[
                    ("Forests", "Forests"),
                    ("Transport", "Transport"),
                    ("Energy", "Energy"),
                    ("Wastes", "Wastes"),
                ],
                default="Forests",
                max_length=10,
                null=True,
            ),
        ),
    ]
