# Generated by Django 4.2.13 on 2024-09-13 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0026_projct_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="level",
        ),
        migrations.RemoveField(
            model_name="project",
            name="users",
        ),
        migrations.CreateModel(
            name="UserProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField(default=1)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zayna.project"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zayna.user"
                    ),
                ),
            ],
        ),
    ]
