# Generated by Django 4.2.13 on 2024-09-13 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0027_user_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_present",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userproject",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participates",
                to="zayna.user",
            ),
        ),
    ]
