# Generated by Django 4.2.13 on 2024-09-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0028_is_present"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stock",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
