# Generated by Django 4.2.13 on 2024-09-16 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0029_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="Network",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("YouTube", "YouTube"),
                            ("X", "X"),
                            ("FB", "FB"),
                            ("Insta", "Insta"),
                            ("LinkedIn", "LinkedIn"),
                            ("TG", "TG"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="networks",
                        to="zayna.user",
                    ),
                ),
            ],
        ),
    ]
