# Generated by Django 4.2.13 on 2024-09-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0030_network"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="income_updated_at",
        ),
        migrations.AlterField(
            model_name="network",
            name="name",
            field=models.CharField(
                choices=[
                    ("YouTube", "YouTube"),
                    ("X", "X"),
                    ("FB", "FB"),
                    ("Insta", "Insta"),
                    ("LinkedIn", "LinkedIn"),
                    ("TG", "TG"),
                    ("TikTok", "TikTok"),
                    ("Pinterst", "Pinterst"),
                ],
                max_length=10,
            ),
        ),
    ]
