# Generated by Django 4.2.13 on 2024-09-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0031_delete_income_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
