# Generated by Django 4.2.13 on 2024-09-17 07:34

from django.db import migrations, models
import zayna.models


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0032_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to=zayna.models.PreserveFilename()
            ),
        ),
    ]
