# Generated by Django 4.2.13 on 2024-09-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0032_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
