# Generated by Django 4.2.13 on 2024-09-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0033_autofield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userproject",
            name="level",
            field=models.IntegerField(default=0),
        ),
    ]
