# Generated by Django 4.2.13 on 2024-09-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0034_default_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="daily_reward_at",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
