# Generated by Django 4.2.13 on 2024-10-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0035_daily"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="mode",
            field=models.CharField(
                choices=[
                    ("Леса", "Леса"),
                    ("Транспорт", "Транспорт"),
                    ("Энергия", "Энергия"),
                    ("Затраты", "Затраты"),
                ],
                default="Леса",
                max_length=10,
                null=True,
            ),
        ),
    ]
