# Generated by Django 4.2.13 on 2024-10-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0036_russian_modes"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="income_by_level",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="project",
            name="price_by_level",
            field=models.JSONField(default=list),
        ),
    ]
