# Generated by Django 4.2.15 on 2024-10-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayna', '0037_price_by_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='mode',
            field=models.CharField(choices=[('Рынок', 'Рынок'), ('Недвижимость', 'Недвижимость'), ('Энергия', 'Энергия'), ('Затраты', 'Затраты')], default='Рынок', max_length=12, null=True),
        ),
    ]
