# Generated by Django 4.2.13 on 2024-10-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0038_market_realty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="logo",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
