# Generated by Django 4.2.13 on 2024-10-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zayna", "0040_float_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="income",
        ),
        migrations.RemoveField(
            model_name="project",
            name="price",
        ),
    ]
